### ISSUE TITLE
Unable to run any Example due to a null in the Run

### ISSUE THREAD

**Issue by xmppjingle** [haumacher/mjSIP#25]
It seems to fail bad here: 
`SipConfig sipConfig = new SipConfig();`

With:
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.mjsip.examples.MiniJukebox.main(MiniJukebox.java:79)
Caused by: java.lang.NullPointerException: inStream parameter is null
	at java.base/java.util.Objects.requireNonNull(Objects.java:235)
	at java.base/java.util.Properties.load(Properties.java:407)
	at org.mjsip.sip.provider.SipStack.<clinit>(SipStack.java:54)
	... 1 more

**Comment by haumacher** [comment]
I think this can only happen, if you build the project without a Maven builder. However, I added some safety code, that prevents to fail the hard way, when doing so. Could you re-test?
